# Generated by Django 3.2.5 on 2021-07-24 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goodsID', models.AutoField(primary_key=True, serialize=False)),
                ('goodsName', models.CharField(max_length=64)),
                ('goodsCategory', models.CharField(max_length=64)),
                ('goodsDescription', models.CharField(max_length=200)),
                ('goodsPrice', models.IntegerField()),
                ('goodsStatus', models.BooleanField()),
                ('goodsLocation', models.CharField(max_length=64)),
                ('goodsPostedTime', models.TimeField(auto_now=True)),
                ('goodsUpdatedTime', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('accountName', models.CharField(max_length=32)),
                ('userPassword', models.CharField(max_length=32)),
                ('userEmail', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingScore', models.IntegerField()),
                ('goodsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodpick.goods')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodpick.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderStatus', models.BooleanField()),
                ('orderTransactionTime', models.TimeField(auto_now=True)),
                ('goodsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodpick.goods')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodpick.user')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='goodsCreateId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodpick.user'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentContent', models.CharField(max_length=200)),
                ('commentTime', models.TimeField(auto_now=True)),
                ('goodsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodpick.goods')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodpick.user')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatContent', models.CharField(max_length=200)),
                ('chatTime', models.TimeField(auto_now=True)),
                ('goodsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodpick.goods')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodpick.user')),
            ],
        ),
    ]
