# Generated by Django 3.2.5 on 2021-07-29 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goodsID', models.AutoField(primary_key=True, serialize=False)),
                ('goodsName', models.CharField(max_length=64)),
                ('goodsCategory', models.CharField(max_length=64)),
                ('goodsDescription', models.CharField(max_length=200)),
                ('goodsPrice', models.IntegerField()),
                ('goodsStatus', models.BooleanField()),
                ('goodsLocation', models.CharField(max_length=64)),
                ('goodsPostedTime', models.TimeField(auto_now=True)),
                ('goodsUpdatedTime', models.TimeField(auto_now=True)),
                ('goodsCreateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingScore', models.IntegerField()),
                ('goodsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodpick.goods')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderStatus', models.BooleanField()),
                ('orderTransactionTime', models.TimeField(auto_now=True)),
                ('goodsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodpick.goods')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentContent', models.CharField(max_length=200)),
                ('commentTime', models.TimeField(auto_now=True)),
                ('goodsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodpick.goods')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatContent', models.CharField(max_length=200)),
                ('chatTime', models.TimeField(auto_now=True)),
                ('goodsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodpick.goods')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
