# Generated by Django 3.2.5 on 2021-07-30 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodpick', '0002_auto_20210729_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('goodsImageID', models.AutoField(primary_key=True, serialize=False)),
                ('goodsImage1', models.ImageField(blank=True, null=True, upload_to='')),
                ('goodsImage2', models.ImageField(blank=True, null=True, upload_to='')),
                ('goodsImage3', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='goodsImageID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='goodpick.productimage'),
        ),
    ]
