# Generated by Django 3.2.5 on 2021-08-02 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodpick', '0003_auto_20210730_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('isMain', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='goods',
            name='goodsImageID',
        ),
        migrations.AlterField(
            model_name='goods',
            name='goodsCategoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodpick.category'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goodsDescription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goodsStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.AddField(
            model_name='goodsimage',
            name='goodsID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodpick.goods'),
        ),
    ]
