# Generated by Django 3.2.6 on 2021-08-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodpick', '0004_auto_20210802_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goodsDescription',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
