# Generated by Django 3.2.5 on 2021-08-08 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodpick', '0004_auto_20210802_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('userProvinceID', models.AutoField(primary_key=True, serialize=False)),
                ('userProvinceName', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='userProvinceID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goodpick.province'),
        ),
    ]
