# Generated by Django 3.2.5 on 2021-08-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodpick', '0005_auto_20210808_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userPhoneNumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
