# Generated by Django 3.2.5 on 2021-08-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodpick', '0005_alter_goods_goodsdescription'),
        ('goodpick', '0006_user_userphonenumber'),
    ]

    operations = [
    ]
